export const english = {
    offers:"offers",
    reserve: "reserve",
    gallery:"gallery",
    contact:"contact",
    about:"about",
    language:"EN",
    title:"Image Hunter",
    underTitle:"The best choice for your special night",
    reserveNow:"reserve now",
    ourOffers:"our offers",
    streaming:"steaming",
    whyUs:"why us",
    whyTsText1:"the best professional team at your service to make sure you get the best.",
    whyTsText2:"the quality of the image is guaranteed with the best cameras brands in the world.",
    whyTsText3:"choose The date of your special day from the calendar and reserve online.",
    whyTsText4:"we will stream live so everyone can watch your wedding.",
    whyTsText5:"we will travel to you anywhere in Tunisia no matter how far you are.",
    whyTsText6:"Discover our amazing offer and choose the one that suits your budget.",
    offer1: "economic offer",
    offer11:"100 photo",
    offer12:"live streaming",
    offer13:"3 HD cameras",
    offer2: "premium offer",
    offer21:"200 photo",
    offer22:"live streaming",
    offer23:"4 HD cameras",
    offer3: "express offer",
    offer31:"150 photo",
    offer32:"live streaming",
    offer33:"3 HD cameras",
    offer1Price: "800 D",
    offer2Price: "1000 D",
    offer3Price: "600 D",
    albums:'albums',
    videos:'videos',
    latestAlbums:'Latest Albums',
    newVideos:'New Videos',
    liveStream:'Live Streaming ',
    viewMore:'view more',
    testimonials:'testimonials',
    testimonials1:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, quaerat quam? Ab aperiam blanditiis, consequuntur delectus deleniti dolorem id itaque maiores, nisi placeat possimus provident sapiente soluta, tenetur vel vero.',
    testimonials2:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, quaerat quam? Ab aperiam blanditiis, consequuntur delectus deleniti dolorem id itaque maiores, nisi placeat possimus provident sapiente soluta, tenetur vel vero.',
    testimonials3:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, quaerat quam? Ab aperiam blanditiis, consequuntur delectus deleniti dolorem id itaque maiores, nisi placeat possimus provident sapiente soluta, tenetur vel vero.',
    testimonials1Job:"Customer",
    testimonials2Job:"Customer",
    testimonials3Job:"Customer",
    reserveDate:'Book your date',
    name:'name',
    phoneNumber:'phone number',
    eMailAddress:'e-mail address',
    subject:'subject',
    yourMsg:'your message ...',
    sendMsg:'send message',
    aboutUs:'about us',
    aboutUsText:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus asperiores eligendi explicabo illum nihil nostrum omnis perspiciatis repudiandae suscipit vitae.',
    recentPosts:'recent Albums',
    address:'address',
    msgSentTitle:'Reservation registered.',
    msgSentCont:'We will contact you via phone and email to confirm your reservation.',
};


export const french = {
    offers:"les offres",
    reserve: "réserver",
    gallery:"galerie",
    contact:"contact",
    about:"à propos",
    language:"FR",
    title:"chasseur d'images",
    underTitle:"le meilleur choix pour votre nuit spéciale",
    reserveNow:"réserver",
    ourOffers:"Nos offres",
    streaming:"steaming",
    whyUs:"pourquoi nous?",
    whyTsText1:"la meilleure équipe professionnelle à votre service pour vous assurer d'obtenir le meilleur.",
    whyTsText2:"la qualité de l'image est garantie avec les meilleures marques d'appareils photo dans le monde.",
    whyTsText3:"choisissez la date de votre jour spécial du calendrier et réservez en ligne.",
    whyTsText4:"nous diffuserons en direct pour que tout le monde puisse regarder votre mariage.",
    whyTsText5:"nous allons voyager vers vous n'importe où en Tunisie, peu importe à quelle distance vous êtes.",
    whyTsText6:"Découvrez notre offre incroyable et choisissez celle qui convient à votre budget.",
    offer1: "offre économique",
    offer11:"100 photos",
    offer12:"diffusion en direct",
    offer13:"3 caméras HD",
    offer2: "offre premium",
    offer21:"200 photos",
    offer22:"diffusion en direct",
    offer23:"4 caméras HDs",
    offer3: "offre expresse",
    offer31:"150 photos",
    offer32:"diffusion en direct",
    offer33:"3 caméras HDs",
    offer1Price: "800 D",
    offer2Price: "1000 D",
    offer3Price: "600 D",
    albums:'albums',
    videos:'videos',
    latestAlbums:'Derniers albums',
    newVideos:'Nouvelles vidéos',
    liveStream:'Live Streaming',
    viewMore:'Afficher plus',
    testimonials:'témoignages',
    testimonials1:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, quaerat quam? Ab aperiam blanditiis, consequuntur delectus deleniti dolorem id itaque maiores, nisi placeat possimus provident sapiente soluta, tenetur vel vero.',
    testimonials2:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, quaerat quam? Ab aperiam blanditiis, consequuntur delectus deleniti dolorem id itaque maiores, nisi placeat possimus provident sapiente soluta, tenetur vel vero.',
    testimonials3:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, quaerat quam? Ab aperiam blanditiis, consequuntur delectus deleniti dolorem id itaque maiores, nisi placeat possimus provident sapiente soluta, tenetur vel vero.',
    testimonials1Job:"Client",
    testimonials2Job:"Client",
    testimonials3Job:"Client",
    reserveDate:'Reservez votre date',
    name:'nom',
    phoneNumber:'numéro de téléphone',
    eMailAddress:'adresse e-mail',
    subject:'sujet',
    yourMsg:'Votre message ...',
    sendMsg:'Envoyer le message',
    aboutUs:'à propos de nous',
    aboutUsText:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus asperiores eligendi explicabo illum nihil nostrum omnis perspiciatis repudiandae suscipit vitae.',
    recentPosts:'Albums récents',
    address:'Adresse',
    msgSentTitle:'Réservation enregistrée.',
    msgSentCont:'Nous vous contacterons par téléphone et par email pour confirmer votre réservation.',
};

